# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbdzcx_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 770)
        Form.setMinimumSize(QtCore.QSize(900, 770))
        Form.setMaximumSize(QtCore.QSize(900, 770))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/地震波.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.glcomboBox = QtWidgets.QComboBox(Form)
        self.glcomboBox.setObjectName("glcomboBox")
        self.horizontalLayout.addWidget(self.glcomboBox)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fwcomboBox = QtWidgets.QComboBox(Form)
        self.fwcomboBox.setObjectName("fwcomboBox")
        self.horizontalLayout.addWidget(self.fwcomboBox)
        self.queryButton = QtWidgets.QPushButton(Form)
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout.addWidget(self.queryButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.escButton = QtWidgets.QPushButton(Form)
        self.escButton.setObjectName("escButton")
        self.horizontalLayout.addWidget(self.escButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.queryTabel = QtWidgets.QTableWidget(Form)
        self.queryTabel.setObjectName("queryTabel")
        self.queryTabel.setColumnCount(0)
        self.queryTabel.setRowCount(0)
        self.verticalLayout.addWidget(self.queryTabel)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.imgWindow = QtWidgets.QWidget(Form)
        self.imgWindow.setMinimumSize(QtCore.QSize(870, 0))
        self.imgWindow.setStyleSheet("")
        self.imgWindow.setObjectName("imgWindow")
        self.verticalLayout.addWidget(self.imgWindow)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(5, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "超越概率："))
        self.label_2.setText(_translate("Form", "选择范围："))
        self.queryButton.setText(_translate("Form", "查询"))
        self.escButton.setText(_translate("Form", "返回"))
        self.label_3.setText(_translate("Form", "反应图谱："))
